### ISSUE TITLE
Tried to run with XGBClassifier, but got a ValueError

### ISSUE THREAD

**Issue by tommyktech** [jodivaso/hybparsimony#1]
First of all, I would like to thank you for creating such a wonderful library. Your library has achieved performance that no others could.

So, I tried to achieve the same with XGBoost and created the following code, but I encountered the following error and couldn’t get it to work. What should I do to make this work?

## Code
<pre>import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split, RepeatedKFold
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from hybparsimony import HYBparsimony, Population
from sklearn.datasets import load_breast_cancer
iris_dataset = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], test_size=0.3,  random_state=42)

def new_complexity(model, nFeatures, **kwargs):
    df_model = model.get_booster().trees_to_dataframe()
    df_model = df_model[df_model.Feature=='Leaf']
    mean_leaves = df_model.groupby('Tree')['Feature'].count().mean()
    num_trees = df_model.Tree.nunique()   
    int_comp = np.min((1E09-1,num_trees*mean_leaves))
    return nFeatures*1E09 + int_comp

from xgboost import XGBClassifier
new_algo = {"estimator": XGBClassifier, # The estimator
                "complexity": new_complexity, # The complexity
                "max_depth": {"range": (3, 10), "type": Population.INTEGER},
                "learning_rate": {"range": (0.01, 0.1), "type": Population.POWER},
                }

HYBparsimony_model = HYBparsimony(algorithm=new_algo,
                                features=iris_dataset.feature_names,
                                cv=RepeatedKFold(n_splits=5, n_repeats=10),
                                n_jobs= 25, #Use 25 cores (one core=one fold)
                                maxiter=2, # Extend to more generations (time consuming)
                                npart = 10,
                                rerank_error=0.001,
                                verbose=1)

HYBparsimony_model.fit(X_train, y_train, time_limit=1.00)</pre>

## Output + Error
<pre>Detected a binary-class problem. Using 'neg_log_loss' as default scoring function.
Running iteration 0
Best model -> Score = -0.124821 Complexity = 26,000,000,167.0 
Iter = 0 -> MeanVal = -0.133193  ValBest = -0.124821   ComplexBest = 26,000,000,167.0 Time(min) = 0.1376
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[56], line 39
     28 HYBparsimony_model = HYBparsimony(algorithm=new_algo,
     29                                 features=iris_dataset.feature_names,
     30                                 cv=RepeatedKFold(n_splits=5, n_repeats=10),
   (...)
     34                                 rerank_error=0.001,
     35                                 verbose=1)
     37 # Search the best hyperparameters and features 
     38 # (increasing 'time_limit' to improve RMSE with high consuming algorithms)
---> 39 HYBparsimony_model.fit(X_train, y_train, time_limit=1.00)

File ~/.pyenv/versions/hybparsimony/lib/python3.10/site-packages/hybparsimony/hybparsimony.py:917, in HYBparsimony.fit(self, X, y, time_limit)
    915 i = np.random.choice(indexes_to_mute)
    916 j = np.random.randint(0, nfs - 1)
--> 917 population._pop[i, nparams + j] = population.random_gen[j](j, feat_mut_thres=self.feat_mut_thres)
    918 fitnessval[i] = np.nan
    919 fitnesstst[i] = np.nan

File ~/.pyenv/versions/hybparsimony/lib/python3.10/site-packages/hybparsimony/util/population.py:98, in Population.__init__.<locals>._trans_mut.<locals>.<lambda>(y, x, **kwargs)
     96 elif params[x]["type"] == Population.POWER:
     97     t.append(np.vectorize(lambda x: pow(10,x), otypes=[float])) # TODO: No tengo claro que esté bien.
---> 98     gen.append(lambda y, x=x, **kwargs: pow(10,np.random.randint(low=self._min[y], high=self._max[y])))
     99 elif params[x]["type"] == Population.CATEGORICAL:
    100     t.append(np.vectorize(lambda y, x=x: y if type(y) is str else params[x]["range"][int(np.trunc(y))], otypes=[str]))

File numpy/random/mtrand.pyx:782, in numpy.random.mtrand.RandomState.randint()

File numpy/random/_bounded_integers.pyx:1334, in numpy.random._bounded_integers._rand_int64()

ValueError: high <= 0</pre>

**Comment by jodivaso** [comment]
Hi,

It seems that the learning rate parameter is the problem here: you specify it as type POWER, but I guess it should be FLOAT since you want to get numbers in the interval [0.01, 0.1]. That is:

`new_algo = {"estimator": XGBClassifier, # The estimator
                "complexity": new_complexity, # The complexity
                "max_depth": {"range": (3, 10), "type": Population.INTEGER},
                "learning_rate": {"range": (0.01, 0.1), "type": Population.FLOAT},
                }`

POWER is intended to be used with list of integers L, where each x in L will correspond to 10^x. That is, if you write:

`new_algo = {"estimator": XGBClassifier, # The estimator
                "complexity": new_complexity, # The complexity
                "max_depth": {"range": (3, 10), "type": Population.INTEGER},
                "learning_rate": {"range": (-3, -1), "type": Population.POWER},
                }`

then, the learning rate will be tuned among the values [0.001, 0.01, 0.1].
 
Hope this helps!

**Comment by jpison** [comment]
You do not need to define the complexity of XGBoost. You can import it directly from 'hybparsimony/util/'.

On the other hand, one of the most important hyperparameters of XGB is 'n_estimators' (number of trees). It is recommended to set the 'learning_rate' to a value that allows an adequate improvement of the metric to be improved (neither too slow, nor too abrupt), and to test the adjustment of the hyperparameters that have to do with: the number of trees ('n_estimator') and regularization hyperparameters that control the complexity of the trees ('max_depth',  'max_leaves', 'min_child_weight', etc. ) or (''gamma', 'subsample', 'colsample_bytree', 'reg_lambda', 'reg_alpha', etc...)... (see: [sklearn hyperparameters](https://xgboost.readthedocs.io/en/stable/python/python_api.html#module-xgboost.sklearn) )


```
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split, RepeatedKFold
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from hybparsimony import HYBparsimony, Population

from sklearn.datasets import load_breast_cancer
iris_dataset = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], test_size=0.3,  random_state=42)

from hybparsimony.util import xgboost_complexity
from xgboost import XGBClassifier
new_algo = {"estimator": XGBClassifier, # The estimator
                "complexity": xgboost_complexity, # The complexity
                "learning_rate": {"value": 0.1, "type": Population.CONSTANT},
                "n_estimators": {"range": (1, 100), "type": Population.INTEGER},
                "max_depth": {"range": (3, 10), "type": Population.INTEGER},
                "gamma": {"range": (0., 10.0), "type": Population.FLOAT},
                "subsample": {"range": (0.0, 0.90), "type": Population.FLOAT},
                }

HYBparsimony_model = HYBparsimony(algorithm=new_algo,
                                features=iris_dataset.feature_names,
                                cv=RepeatedKFold(n_splits=5, n_repeats=10),
                                n_jobs= 25, #Use 25 cores (one core=one fold)
                                maxiter=10, # Extend to more generations (time consuming)
                                npart = 10,
                                rerank_error=0.001,
                                verbose=1)

HYBparsimony_model.fit(X_train, y_train, time_limit=1.00)
```

**Comment by tommyktech** [comment]
@jodivaso 
Thank you for your reply. I see, I was entering the learning_rate value incorrectly. I ran the code you provided, and it worked perfectly. I appreciate your guidance.

@jpison 
Thank you for showing me how to import the complexity of xgboost. I'll also refer to the information you provided about hyperparameters 🙇
